// 	int printf(const char *format, ...);
// 发送格式化输出到标准输出 stdout。

// int fprintf(FILE *__restrict, const char *__restrict, ...);

// int sprintf(char *__restrict, const char *__restrict, ...);

// int snprintf(char *__restrict, size_t, const char *__restrict, ...);

// 	int vprintf(const char *format, va_list arg);
// 使用参数列表发送格式化输出到标准输出 stdout。


// 	int vfprintf(FILE *stream, const char *format, va_list arg);
// 使用参数列表发送格式化输出到流 stream 中。


// int vsprintf(char *str, const char *format, va_list arg);
// 使用参数列表发送格式化输出到字符串。

// int vsnprintf(char *__restrict, size_t, const char *__restrict, __isoc_va_list);
